package compiler

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/andrioid/gastro/internal/codegen"
	"github.com/andrioid/gastro/internal/parser"
	"github.com/andrioid/gastro/internal/router"
)

// Compile reads all .gastro files from a project directory, processes them
// through the parser and code generator, and writes the output to outputDir.
func Compile(projectDir, outputDir string) error {
	// Ensure output subdirectories exist
	for _, sub := range []string{"pages", "components", "templates"} {
		if err := os.MkdirAll(filepath.Join(outputDir, sub), 0o755); err != nil {
			return fmt.Errorf("creating output directory: %w", err)
		}
	}

	// Discover all .gastro files
	pageFiles, err := discoverFiles(filepath.Join(projectDir, "pages"), "pages")
	if err != nil {
		return fmt.Errorf("discovering pages: %w", err)
	}

	componentFiles, err := discoverFiles(filepath.Join(projectDir, "components"), "components")
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("discovering components: %w", err)
	}

	// Process each file
	allFiles := append(pageFiles, componentFiles...)
	for _, relPath := range allFiles {
		absPath := filepath.Join(projectDir, relPath)
		if err := compileFile(absPath, relPath, outputDir); err != nil {
			return fmt.Errorf("compiling %s: %w", relPath, err)
		}
	}

	// Detect static asset directory
	hasStatic := false
	if info, err := os.Stat(filepath.Join(projectDir, "static")); err == nil && info.IsDir() {
		hasStatic = true
	}

	// Generate routes file
	routes := router.BuildRoutes(pageFiles)
	if err := generateRoutesFile(routes, hasStatic, outputDir); err != nil {
		return fmt.Errorf("generating routes: %w", err)
	}

	return nil
}

// discoverFiles walks a directory and returns relative paths of all .gastro files.
func discoverFiles(dir, prefix string) ([]string, error) {
	var files []string

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".gastro") {
			return nil
		}

		rel, err := filepath.Rel(filepath.Dir(dir), path)
		if err != nil {
			return err
		}
		files = append(files, rel)
		return nil
	})

	return files, err
}

func compileFile(absPath, relPath, outputDir string) error {
	content, err := os.ReadFile(absPath)
	if err != nil {
		return err
	}

	// Parse
	file, err := parser.Parse(relPath, string(content))
	if err != nil {
		return err
	}

	// Analyze frontmatter
	info, err := codegen.AnalyzeFrontmatter(file.Frontmatter)
	if err != nil {
		return err
	}

	// Transform template body
	transformedBody, err := codegen.TransformTemplate(file.TemplateBody, file.Uses)
	if err != nil {
		return err
	}

	// Write template file
	templateName := strings.TrimSuffix(relPath, ".gastro")
	templateName = strings.ReplaceAll(templateName, "/", "_")
	templatePath := filepath.Join(outputDir, "templates", templateName+".html")
	if err := os.WriteFile(templatePath, []byte(transformedBody), 0o644); err != nil {
		return err
	}

	// Generate handler Go code
	file.TemplateBody = transformedBody
	handlerCode, err := codegen.GenerateHandler(file, info)
	if err != nil {
		return err
	}

	// All generated .go files go flat in the output directory (same package)
	goFileName := strings.TrimSuffix(relPath, ".gastro")
	goFileName = strings.ReplaceAll(goFileName, "/", "_")
	goFileName = strings.ReplaceAll(goFileName, "[", "")
	goFileName = strings.ReplaceAll(goFileName, "]", "")
	goFileName = strings.ReplaceAll(goFileName, "-", "_")
	goFilePath := filepath.Join(outputDir, goFileName+".go")
	if err := os.WriteFile(goFilePath, []byte(handlerCode), 0o644); err != nil {
		return err
	}

	return nil
}

// routesData is the data passed to routesTmpl.
type routesData struct {
	Routes    []router.Route
	HasStatic bool
}

var routesTmpl = template.Must(template.New("routes").Parse(`// Code generated by gastro. DO NOT EDIT.
package gastro

import (
	"html/template"
	"net/http"

	gastroRuntime "github.com/andrioid/gastro/pkg/gastro"
)

// Option configures the generated router.
type Option func(*config)

type config struct {
	funcs template.FuncMap
}

// WithFuncs registers additional template helper functions.
// User-provided functions override built-in defaults with the same name.
func WithFuncs(fm template.FuncMap) Option {
	return func(c *config) {
		for k, v := range fm {
			c.funcs[k] = v
		}
	}
}

// Routes returns an http.Handler with all gastro page routes and static assets.
func Routes(opts ...Option) http.Handler {
	cfg := &config{
		funcs: gastroRuntime.DefaultFuncs(),
	}
	for _, opt := range opts {
		opt(cfg)
	}

	_ = cfg // will be used for template funcs once templates support it

	mux := http.NewServeMux()
{{- if .HasStatic }}
	mux.Handle("GET /static/", http.StripPrefix("/static/", http.FileServer(http.Dir("static"))))
{{- end }}
{{- range .Routes }}
	mux.HandleFunc("{{ .Pattern }}", {{ .FuncName }})
{{- end }}
	return mux
}
`))

func generateRoutesFile(routes []router.Route, hasStatic bool, outputDir string) error {
	f, err := os.Create(filepath.Join(outputDir, "routes.go"))
	if err != nil {
		return err
	}
	defer f.Close()

	return routesTmpl.Execute(f, routesData{
		Routes:    routes,
		HasStatic: hasStatic,
	})
}
