id = "gastro"
name = "Gastro"
version = "0.1.0"
schema_version = 1
authors = ["Andri Oskarsson <andri@andrioid.net>"]
description = "Gastro language support: syntax highlighting and LSP integration"
repository = "https://github.com/andrioid/gastro"

[grammars.gastro]
repository = "https://github.com/andrioid/gastro"
path = "tree-sitter-gastro"
rev = "54d91b2ba38946652d993838c6d54a1b9588f26c"

[language_servers.gastro-lsp]
name = "Gastro Language Server"
languages = ["Gastro"]
