package codegen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"strings"
	"text/template"

	gastroParser "github.com/andrioid/gastro/internal/parser"
)

// UseInfo holds the template-friendly data for a component use declaration.
type UseInfo struct {
	Name     string // e.g. "Layout"
	FuncName string // e.g. "componentLayout"
}

// GenerateHandler produces Go source code for a page handler or component
// render function from a parsed .gastro file and its frontmatter analysis.
// isComponent indicates whether this file should generate a component render
// function. This is typically info.IsComponent, but the compiler may override
// it for files in components/ that have no frontmatter.
func GenerateHandler(file *gastroParser.File, info *FrontmatterInfo, isComponent bool) (string, error) {
	funcName := HandlerFuncName(file.Filename)
	frontmatter := rewriteFrontmatter(file.Frontmatter, info, isComponent)

	// Extract hoisted type declarations for components.
	// Rename the type to avoid collisions between components in the same package.
	var hoistedTypes string
	propsTypeName := info.PropsTypeName
	if isComponent && propsTypeName != "" {
		_, hoistedTypes = HoistTypeDeclarations(file.Frontmatter)
		hoistedTypes = strings.TrimSpace(hoistedTypes)
		uniqueName := funcName + strings.ToUpper(propsTypeName[:1]) + propsTypeName[1:]
		hoistedTypes = strings.Replace(hoistedTypes, "type "+propsTypeName+" ", "type "+uniqueName+" ", 1)
		propsTypeName = uniqueName
	}

	// Build use info for pages that import components
	var uses []UseInfo
	for _, u := range file.Uses {
		uses = append(uses, UseInfo{
			Name:     u.Name,
			FuncName: HandlerFuncName(u.Path),
		})
	}

	data := generateData{
		PackageName:   "gastro",
		FuncName:      funcName,
		ExportedName:  ExportedComponentName(funcName),
		Imports:       file.Imports,
		Frontmatter:   frontmatter,
		ExportedVars:  info.ExportedVars,
		TemplateBody:  file.TemplateBody,
		IsPage:        info.IsPage,
		PropsTypeName: propsTypeName,
		IsComponent:   isComponent,
		HoistedTypes:  hoistedTypes,
		Uses:          uses,
	}

	tmpl := handlerTmpl
	if isComponent {
		tmpl = componentTmpl
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("generating handler for %s: %w", file.Filename, err)
	}

	return buf.String(), nil
}

type generateData struct {
	PackageName   string
	FuncName      string
	ExportedName  string // e.g. "PostCard" — exported name for Render API
	Imports       []string
	Frontmatter   string
	ExportedVars  []VarInfo
	TemplateBody  string
	IsPage        bool
	IsComponent   bool
	PropsTypeName string    // e.g. "Props" — from type Props struct in the frontmatter
	HoistedTypes  string    // e.g. "type Props struct { Title string }"
	Uses          []UseInfo // component imports used by this page
}

// handlerTmpl generates HTTP handlers that stream output directly to the response.
// Pages stream via Execute(w, ...) which is more efficient and follows Go's
// http.Handler conventions. This is intentionally separate from componentTmpl
// because the I/O model is fundamentally different (streaming vs buffering).
var handlerTmpl = template.Must(template.New("handler").Parse(`// Code generated by gastro. DO NOT EDIT.
package {{ .PackageName }}

import (
	"log"
	"net/http"
	"html/template"

	gastroRuntime "github.com/andrioid/gastro/pkg/gastro"
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)

// Suppress unused import warnings
var _ = gastroRuntime.NewContext
var _ http.Handler
var _ = template.Must
var _ = log.Println

func {{ .FuncName }}(w http.ResponseWriter, r *http.Request) {
	defer gastroRuntime.Recover(w, r)
	{{- if .IsPage }}
	ctx := gastroRuntime.NewContext(w, r)
	_ = ctx
	{{ end }}
	{{ .Frontmatter }}

	__data := map[string]any{
	{{- range .ExportedVars }}
		"{{ .Name }}": {{ .Name }},
	{{- end }}
	}

	if __err := __gastro_getTemplate("{{ .FuncName }}").Execute(w, __data); __err != nil {
		log.Printf("gastro: page {{ .FuncName }}: template execution failed: %v", __err)
	}
}
`))

// componentTmpl generates render functions that return template.HTML.
// Components buffer into a bytes.Buffer because they must return the complete
// HTML string to the caller (parent template or Render API). This is intentionally
// separate from handlerTmpl because the I/O model is fundamentally different
// (buffering vs streaming).
var componentTmpl = template.Must(template.New("component").Parse(`// Code generated by gastro. DO NOT EDIT.
package {{ .PackageName }}

import (
	"bytes"
	"html/template"
	"log"

	gastroRuntime "github.com/andrioid/gastro/pkg/gastro"
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)

// Suppress unused import warnings
var _ = gastroRuntime.DefaultFuncs
var _ bytes.Buffer
var _ = template.Must
var _ = log.Println

{{- if .HoistedTypes }}

{{ .HoistedTypes }}
{{- end }}

{{- if .PropsTypeName }}

// {{ .ExportedName }}Props is the exported type alias for use with Render.
type {{ .ExportedName }}Props = {{ .PropsTypeName }}
{{- end }}

func {{ .FuncName }}(propsMap map[string]any) template.HTML {
	var __children template.HTML
	if __c, __ok := propsMap["__children"]; __ok {
		__children, _ = __c.(template.HTML)
		delete(propsMap, "__children")
	}
	_ = __children

	{{- if .PropsTypeName }}
	__props, __err := gastroRuntime.MapToStruct[{{ .PropsTypeName }}](propsMap)
	if __err != nil {
		log.Printf("gastro: component {{ .FuncName }}: %v", __err)
		return ""
	}
	_ = __props
	{{- end }}

	{{ .Frontmatter }}

	__data := map[string]any{
	{{- range .ExportedVars }}
		"{{ .Name }}": {{ .Name }},
	{{- end }}
		"Children": __children,
	}

	var __buf bytes.Buffer
	if __err := __gastro_getTemplate("{{ .FuncName }}").Execute(&__buf, __data); __err != nil {
		log.Printf("gastro: component {{ .FuncName }}: template execution failed: %v", __err)
		return ""
	}
	return template.HTML(__buf.String())
}
`))

// markerKind distinguishes between different gastro compile-time markers.
type markerKind int

const (
	markerContext   markerKind = iota // gastro.Context() — strip the line
	markerPropsCall                   // gastro.Props() — rewrite to __props
)

// markerLine records an AST-detected gastro marker with its frontmatter line
// number and the kind of rewrite to apply.
type markerLine struct {
	line int // 1-indexed line within the frontmatter
	kind markerKind
}

// detectMarkerLines parses the frontmatter with go/ast and returns precise
// line numbers for gastro.Context() calls. gastro.Props() rewrites are handled
// separately via string replacement after AST detection confirms their presence.
func detectMarkerLines(frontmatter string) []markerLine {
	// Wrap the raw frontmatter in a function body without hoisting types.
	// Type declarations inside functions are valid Go and the parser handles
	// them correctly. This preserves original line numbers for marker rewrites.
	prefix := "package __gastro\nfunc __handler() {\n"
	prefixLineCount := strings.Count(prefix, "\n")
	src := prefix + frontmatter + "\n}"

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "frontmatter.go", src, parser.AllErrors)
	if err != nil {
		return nil
	}

	var markers []markerLine

	ast.Inspect(file, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}

		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}

		ident, ok := sel.X.(*ast.Ident)
		if !ok {
			return true
		}

		if ident.Name == "gastro" && sel.Sel.Name == "Context" {
			line := fset.Position(call.Pos()).Line - prefixLineCount
			markers = append(markers, markerLine{line: line, kind: markerContext})
		}

		return true
	})

	return markers
}

// hasGastroPropsCall returns true if the frontmatter contains a gastro.Props()
// call, as detected by the AST. Used to confirm that string-based replacement
// is safe.
func hasGastroPropsCall(frontmatter string) bool {
	prefix := "package __gastro\nfunc __handler() {\n"
	src := prefix + frontmatter + "\n}"

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "frontmatter.go", src, parser.AllErrors)
	if err != nil {
		return false
	}

	found := false
	ast.Inspect(file, func(n ast.Node) bool {
		if found {
			return false
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		if isGastroPropsCall(call) {
			found = true
			return false
		}
		return true
	})
	_ = fset
	return found
}

// rewriteGastroProps replaces gastro.Props() calls with __props in the
// frontmatter string. The AST is used first to confirm that a real call
// exists (not just the text in a comment/string), then string replacement
// handles the actual rewrite to preserve formatting.
//
// Handles:
//   - p := gastro.Props()          → p := __props
//   - Title := gastro.Props().Title → Title := __props.Title
//   - fmt.Sprintf("%d", gastro.Props().X + 1) → fmt.Sprintf("%d", __props.X + 1)
func rewriteGastroProps(frontmatter string) string {
	if !hasGastroPropsCall(frontmatter) {
		return frontmatter
	}

	// Parse to find exact call text patterns to replace. We use AST to find
	// the calls, then compute what source text to replace based on call type.
	prefix := "package __gastro\nfunc __handler() {\n"
	prefixLen := len(prefix)
	src := prefix + frontmatter + "\n}"

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "frontmatter.go", src, parser.AllErrors)
	if err != nil {
		return frontmatter
	}

	// Collect replacements as (start, end) byte offsets in the frontmatter
	type replacement struct {
		start int // byte offset in frontmatter
		end   int // byte offset in frontmatter (exclusive)
	}
	var replacements []replacement

	ast.Inspect(file, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		if !isGastroPropsCall(call) {
			return true
		}

		// Convert from source (with prefix) positions to frontmatter positions
		callStart := int(call.Pos()) - 1 - prefixLen // token.Pos is 1-indexed
		callEnd := int(call.End()) - 1 - prefixLen
		if callStart >= 0 && callEnd <= len(frontmatter) {
			replacements = append(replacements, replacement{start: callStart, end: callEnd})
		}

		return true
	})

	if len(replacements) == 0 {
		return frontmatter
	}

	// Apply replacements in reverse order to preserve byte offsets
	result := frontmatter
	for i := len(replacements) - 1; i >= 0; i-- {
		r := replacements[i]
		result = result[:r.start] + "__props" + result[r.end:]
	}

	return result
}

// rewriteFrontmatter transforms code-gen markers in the frontmatter:
// - gastro.Context() lines are stripped (the handler template generates ctx)
// - gastro.Props() calls are replaced with __props
// - Type declarations are stripped for components (hoisted to package level)
//
// Marker detection uses go/ast for precision (no false positives on strings,
// comments, or similar identifiers). Type stripping uses line-based brace
// tracking which is correct for Go type declarations.
func rewriteFrontmatter(frontmatter string, info *FrontmatterInfo, isComponent bool) string {
	contextMarkers := detectMarkerLines(frontmatter)

	// Build a set of context marker lines for O(1) lookup
	contextLines := make(map[int]bool, len(contextMarkers))
	for _, m := range contextMarkers {
		if m.kind == markerContext {
			contextLines[m.line] = true
		}
	}

	// Rewrite gastro.Props() calls to __props
	frontmatter = rewriteGastroProps(frontmatter)

	lines := strings.Split(frontmatter, "\n")
	var kept []string
	inType := false
	braceDepth := 0

	for i, line := range lines {
		lineNum := i + 1 // 1-indexed

		// For components, skip type declarations (hoisted to package level)
		if isComponent {
			trimmed := strings.TrimSpace(line)
			if !inType && strings.HasPrefix(trimmed, "type ") {
				inType = true
				braceDepth = 0
			}
			if inType {
				braceDepth += strings.Count(line, "{") - strings.Count(line, "}")
				if braceDepth <= 0 {
					inType = false
				}
				continue
			}
		}

		// Strip gastro.Context() lines
		if contextLines[lineNum] {
			continue
		}

		kept = append(kept, line)
	}

	return strings.TrimSpace(strings.Join(kept, "\n"))
}

// ExportedComponentName derives an exported name from a component function name.
// For example: "componentPostCard" -> "PostCard"
func ExportedComponentName(funcName string) string {
	return strings.TrimPrefix(funcName, "component")
}

// StructField represents a field in a parsed Props struct.
type StructField struct {
	Name string
	Type string
}

// ParseStructFields extracts field names and types from a hoisted type
// declaration string like "type FooProps struct {\n    Title string\n    Count int\n}".
func ParseStructFields(hoistedTypes string) []StructField {
	lines := strings.Split(hoistedTypes, "\n")
	var fields []StructField
	inStruct := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.Contains(trimmed, "struct {") {
			inStruct = true
			continue
		}
		if inStruct && trimmed == "}" {
			break
		}
		if !inStruct {
			continue
		}

		// Parse "FieldName FieldType" lines
		parts := strings.Fields(trimmed)
		if len(parts) >= 2 {
			fields = append(fields, StructField{
				Name: parts[0],
				Type: parts[1],
			})
		}
	}

	return fields
}

// HandlerFuncName derives a Go function name from a .gastro file path.
// For pages: "pages/index.gastro" -> "pageIndex"
// For components: "components/card.gastro" -> "componentCard"
func HandlerFuncName(filename string) string {
	name := filename
	name = strings.TrimSuffix(name, ".gastro")
	name = strings.ReplaceAll(name, "[", "")
	name = strings.ReplaceAll(name, "]", "")

	// Determine prefix based on directory
	var prefix string
	if strings.HasPrefix(name, "pages/") {
		prefix = "page"
		name = strings.TrimPrefix(name, "pages/")
	} else if strings.HasPrefix(name, "components/") {
		prefix = "component"
		name = strings.TrimPrefix(name, "components/")
	} else {
		prefix = "gastro"
	}

	// Split on / and - to create camelCase segments
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '/' || r == '-'
	})

	var result strings.Builder
	result.WriteString(prefix)

	for _, part := range parts {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}

	return result.String()
}
