package codegen

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/andrioid/gastro/internal/parser"
)

// GenerateHandler produces Go source code for a page handler or component
// render function from a parsed .gastro file and its frontmatter analysis.
func GenerateHandler(file *parser.File, info *FrontmatterInfo) (string, error) {
	funcName := handlerFuncName(file.Filename)
	frontmatter := rewriteFrontmatter(file.Frontmatter, info)

	data := generateData{
		PackageName:  "gastro",
		FuncName:     funcName,
		Imports:      file.Imports,
		Frontmatter:  frontmatter,
		ExportedVars: info.ExportedVars,
		TemplateBody: file.TemplateBody,
		IsPage:       info.IsPage,
		IsComponent:  info.IsComponent,
	}

	var buf strings.Builder
	if err := handlerTmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("generating handler for %s: %w", file.Filename, err)
	}

	return buf.String(), nil
}

type generateData struct {
	PackageName  string
	FuncName     string
	Imports      []string
	Frontmatter  string
	ExportedVars []VarInfo
	TemplateBody string
	IsPage       bool
	IsComponent  bool
}

var handlerTmpl = template.Must(template.New("handler").Parse(`// Code generated by gastro. DO NOT EDIT.
package {{ .PackageName }}

import (
	"net/http"
	"html/template"

	gastroRuntime "github.com/andrioid/gastro/pkg/gastro"
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)

// Suppress unused import warnings
var _ = gastroRuntime.NewContext
var _ http.Handler
var _ = template.Must

var {{ .FuncName }}Template = template.Must(template.New("{{ .FuncName }}").Funcs(gastroRuntime.DefaultFuncs()).Parse(` + "`" + `{{ .TemplateBody }}` + "`" + `))

func {{ .FuncName }}(w http.ResponseWriter, r *http.Request) {
	defer gastroRuntime.Recover(w, r)
	{{- if .IsPage }}
	ctx := gastroRuntime.NewContext(w, r)
	_ = ctx
	{{ end }}
	{{ .Frontmatter }}

	__data := map[string]any{
	{{- range .ExportedVars }}
		"{{ .Name }}": {{ .Name }},
	{{- end }}
	}

	{{ .FuncName }}Template.Execute(w, __data)
}
`))

// rewriteFrontmatter transforms code-gen markers in the frontmatter:
// - gastro.Context() becomes a reference to the already-declared ctx
// - gastro.Props[T]() is rewritten to the props unpacking code
// It also strips the marker lines since they're handled by the template.
func rewriteFrontmatter(frontmatter string, info *FrontmatterInfo) string {
	lines := strings.Split(frontmatter, "\n")
	var kept []string

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip gastro.Context() — it's generated in the handler template
		if strings.Contains(trimmed, "gastro.Context()") {
			continue
		}

		// Skip gastro.Props[...]() — will be handled by component generation
		if strings.Contains(trimmed, "gastro.Props[") {
			continue
		}

		kept = append(kept, line)
	}

	return strings.TrimSpace(strings.Join(kept, "\n"))
}

// handlerFuncName derives a Go function name from a .gastro file path.
// For pages: "pages/index.gastro" -> "pageIndex"
// For components: "components/card.gastro" -> "componentCard"
func handlerFuncName(filename string) string {
	name := filename
	name = strings.TrimSuffix(name, ".gastro")
	name = strings.ReplaceAll(name, "[", "")
	name = strings.ReplaceAll(name, "]", "")

	// Determine prefix based on directory
	var prefix string
	if strings.HasPrefix(name, "pages/") {
		prefix = "page"
		name = strings.TrimPrefix(name, "pages/")
	} else if strings.HasPrefix(name, "components/") {
		prefix = "component"
		name = strings.TrimPrefix(name, "components/")
	} else {
		prefix = "gastro"
	}

	// Split on / and - to create camelCase segments
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '/' || r == '-'
	})

	var result strings.Builder
	result.WriteString(prefix)

	for _, part := range parts {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}

	return result.String()
}
